# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      stack:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'frontend | backend'
        # Input has to be provided for the workflow to run
        required: true
      app:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'trablina | trablina-frontend'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projeto-vidracaria/${{ github.event.inputs.stack }}

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2
    

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          **/node_modules
          **/.eslintcache
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
         ${{ runner.os }}-yarn-
    - name: Build
      run: |
        npm install
        npm run build
        
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: 2af73ae6-0379-4de9-b09a-5999c1ecb674
        heroku_app_name: "${{ github.event.inputs.app }}"
        heroku_email: thiagosiqueira@unifei.edu.br
        appdir: "./projeto-vidracaria/${{ github.event.inputs.stack }}"
